function filesize_reducer_hpc_pipeline(data_folder)

        matlab_name=fullfile(data_folder,'features_out.mat');
        if exist(matlab_name)
            load(matlab_name)

                    clear angle_1d angle_image_kurt_out angle_image_lq_out angle_image_median_out...
                    angle_image_skew_out angle_image_std_out angle_image_uq_out angle_median_X...
                    angle_median_Y branch_labels branches_curvature branchpoint_image...
                    bw bw_a bw_a_filled bw_b bw_b_filled bw_c bw_c_filled bw_d bw_d_filled...
                    bw_filled curvature_dis curvature_image_kurt_out curvature_image_lq_out curvature_image_median_out...
                    curvature_image_skew_out curvature_image_std_out curvature_image_uq_out curvature_X...
                    curvature_Y  end_to_end_angle_continuum end_to_end_angle_matrix end_to_end_angles...
                    end_to_end_x_derivative_continuum end_to_end_x_derivative_matrix end_to_end_y_derivative_continuum...
                    end_to_end_y_derivative_matrix endpoints_curvature endpoints_labels fibre_matrix_zero g g1 g2 g3 index...
                    index1 index2 index_remove input L L1 L_remove label_edge local_angles local_x_derivative_continuum...
                    local_x_derivative_matrix local_y_derivative_continuum local_y_derivative_matrix M1...
                    no_holes_matrix plotted_matrix square_matrix Ufm ys1 ys2 Z1 Z2
            save(matlab_name);
        end
end